### ISSUE TITLE
Kafka distributed connect rest calls are not working 

### ISSUE THREAD

**Issue by pmuthal** [confluentinc/kafka#100]
Hi , 

I am trying to call the kafka rest url post running the connector using url "/connector" post method below is the request details. 

POST /connectors HTTP/1.1
 HOST: 10.10.10.122:8094
 content-type: application/json
 accept: application/json
 content-length: 450
 
 { "name":"piyush",
 "config":{
 "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
 "tasks.max": "1",
 "connection.url": "jdbc:sqlserver:///10.10.5.105:1433;DatabaseName=Solution_Retail;user=pocsql;password=PS@info987",
 "mode":"incrementing",
 "incrementing.column.name": "SHOPPING_TRANSACTION_LINE_ID",
 "topic.prefix": "solution_retail_v1_",
 "table.whitelist": "BASE_FACT_SHOPPING_TRANSACTION_LINE"
 }
 }

I am getting error as follows 

com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')

Please guide me to solve the issue.

thanks ,

**Comment by ewencp** [comment]
How are you making the request? Do you have a snippet of source code we could check? Since `<` doesn't appear anywhere in your request, it seems like it must be getting mangled somehow.

**Comment by pmuthal** [comment]
I am using rest client of Google Chrome.

**Comment by ewencp** [comment]
@pmuthal Are you referring to an extension or something built in to Chrome. There are many extensions for making REST requests from Chrome.

**Comment by pmuthal** [comment]
I am using Advance Rest client application of chrome

**Comment by ewencp** [comment]
@pmuthal There shouldn't be any difference in how the API works between standalone and distributed mode, but perhaps a specific client is triggering this. If you're still having this issues, could you follow up on our [community mailing list](https://groups.google.com/forum/#!forum/confluent-platform)?
