### ISSUE TITLE
Handling for compaction and offsets with negative lag

### ISSUE THREAD

**Issue by mikesparr** [confluentinc/kafka#101]
I notice that after log compaction the offset and log size mismatch so lag counts go haywire. What, if anything, is being done to possibly reset consumer offsets if they are greater than the topic offset, to reset to equal no greater than the topic offset?

I suggest that consumer offsets can never be greater than topic offset so must reset if a compaction occurs, or other event that would make them unusable.

~~~
ubuntu@db1:~$ kafka-consumer-offset-checker --topic rets.wvmls.PhotoEditEvent --group etl-photos --zookeeper queue2:2181

Group           Topic                          Pid Offset          logSize         Lag             Owner
etl-photos      rets.wvmls.PhotoEditEvent      0   2020            1611            -409            none
etl-photos      rets.wvmls.PhotoEditEvent      1   2128            1667            -461            none
etl-photos      rets.wvmls.PhotoEditEvent      2   2239            1653            -586            none
etl-photos      rets.wvmls.PhotoEditEvent      3   3787            1678            -2109           none
etl-photos      rets.wvmls.PhotoEditEvent      4   1917            1622            -295            none
etl-photos      rets.wvmls.PhotoEditEvent      5   2370            1684            -686            none
etl-photos      rets.wvmls.PhotoEditEvent      6   2388            1821            -567            none
etl-photos      rets.wvmls.PhotoEditEvent      7   1540            1690            150             none
etl-photos      rets.wvmls.PhotoEditEvent      8   921             1730            809             none
~~~

**Comment by ewencp** [comment]
@mikesparr You'll probably have more luck on the [Confluent](https://groups.google.com/forum/#!forum/confluent-platform) or [Kafka mailing lists](http://kafka.apache.org/contact.html) -- this repository is just a mirror of the main Kafka repository where we tag Confluent releases.

I'm not sure I entirely understand the issue you are raising. When a topic is compacted, the offsets of messages don't change. Some messages are deleted, but consumers can continue to read even if they were at an offset which is now removed -- they will simply read whatever message that still exists and is next in the stream.

**Comment by ewencp** [comment]
@mikesparr Going to close this as I haven't heard back in awhile and this repository isn't normally monitored for issues as it is just for mirroring and tagging Confluent-specific releases. If you haven't already followed up there, the [Confluent community mailing list](https://groups.google.com/forum/#!forum/confluent-platform) would be the best place to ask follow up questions.
