### ISSUE TITLE
Update rocksdb JNI dependency

### ISSUE THREAD

**Issue by clumsy** [confluentinc/kafka#102]
4.4.1 is way too old and has known issues that has been fixed.
For example there are `EXCEPTION_ACCESS_VIOLATION`s due to unset `nativeHandler_`s when run with Windows dll.
4.8.0 is the latest available version and seem to work fine.
More details available [here](https://github.com/facebook/rocksdb/issues/1221).

**Comment by ijuma** [comment]
Good to know that there have been fixed since 4.4.1. Note that 4.4.1 was the most recent released version in April, so not that old. :) See the following discussion:

https://github.com/facebook/rocksdb/issues/1075

**Comment by ijuma** [comment]
Please follow along here: https://github.com/apache/kafka/pull/1647, thanks for the report. In the future, it may be best to file issues in the upstream project: https://issues.apache.org/jira/browse/KAFKA
