### ISSUE TITLE
KafkaConsumer commitAsync may not require acquire() and could be thread safe

### ISSUE THREAD

**Issue by joychugh** [confluentinc/kafka#80]
Looking at the code bellow, I think the commitAsync method is threadsafe as the only thing it modifies is 
```java
this.subscriptions.needRefreshCommits();
```
If two threads come in and set the needRefreshCommits(), I don't see any harm in setting that variable to true twice since none of them depend on it within this flow to complete.

This maybe true also for commitSync() methods.

Related Code:
https://github.com/confluentinc/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java#L933
https://github.com/confluentinc/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinator.java#L313-L314

**Comment by ewencp** [comment]
@joychugh Thanks for the suggestion. If you dig into all the methods that are invoked by an `commitAsync` call, there is other stuff that it triggers that wouldn't be thread safe. For example, it has to send the offset commit request via `ConsumerNetworkClient` (and `NetworkClient` inside `ConsumerNetworkClient`). Those classes will maintain lists of the sent messages, and adding to those queues will not be thread safe.

More generally, even if it happened to be threadsafe right now, we aren't providing any thread safety guarantees for any of the methods in the API -- users shouldn't rely on behavior that is an implementation detail that could change with future versions. The `acquire()` and `release()` calls are used to try to warn people when they are doing something that is unsupported (and aren't even guaranteed to catch all such misuse).

By the way, generally you'll want to report issues like this to the [Apache JIRA](https://issues.apache.org/jira/browse/KAFKA) or just raise the issue on the [mailing lists]() if you aren't sure whether you should file an issue. This repository is primarily used to provide a set of tags for the Confluent Platform releases so users know exactly what code they are using.

**Comment by ijuma** [comment]
Closing (please continue the discussion in the Apache JIRA of mailing lists).
