### ISSUE TITLE
 Confluent 2.0: Kafka unable to create SSL EndPoint in EC2 (using advertised.host.name property)

### ISSUE THREAD

**Issue by kevinpauli** [confluentinc/kafka#83]
I'm trying to get Kafka working in EC2 over SSL, using confluent-2.0.0-2.11.7.  Ubuntu 14.04 LTS, oracle java 1.8.0_66

In etc/kafka/server.properties, I have listeners=PLAINTEXT://:9092,SSL://:9093

Normally I see this

    INFO Registered broker 0 at path /brokers/ids/0 with addresses: PLAINTEXT -> EndPoint(localhost,9092,PLAINTEXT),SSL -> EndPoint(localhost,9093,SSL) (kafka.utils.ZkUtils)

But this broker is in EC2, and therefore to connect to it from outside of EC2 I need to set advertised.host.name to the public DNS.  As soon as I set advertised.host.name=ec2-54-164-3-183.compute-1.amazonaws.com (no other changes) it no longer creates the SSL EndPoint:

    INFO Registered broker 0 at path /brokers/ids/0 with addresses: PLAINTEXT -> EndPoint(ec2-54-164-3-183.compute-1.amazonaws.com,9092,PLAINTEXT) (kafka.utils.ZkUtils)

So, just to break this down:

Clients connecting locally within EC2 over PLAINTEXT - works
Clients connecting locally within EC2 over SSL - works
Clients connecting remotely to EC2 via public DNS over PLAINTEXT - works
Clients connecting remotely to EC2 via public DNS over SSL - does NOT work
  
I turned on DEBUG (and attached the startup log). Nothing jumps out at me.  We do see this:

    [2016-01-15 15:54:53,845] INFO Awaiting socket connections on 0.0.0.0:9093. (kafka.network.Acceptor)

So it is at least trying... but later on we see there is no SSL EndPoint actually created:

    [2016-01-15 15:54:54,381] INFO Registered broker 0 at path /brokers/ids/0 with addresses: PLAINTEXT -> EndPoint(ec2-54-164-3-183.compute-1.amazonaws.com,9092,PLAINTEXT) (kafka.utils.ZkUtils)

I also attached the server.properties for reference.

[server.properties.txt](https://github.com/confluentinc/kafka/files/92170/server.properties.txt)
[no-ssl-endpoint.log.txt](https://github.com/confluentinc/kafka/files/92171/no-ssl-endpoint.log.txt)

**Comment by ewencp** [comment]
@kevinpauli I think if you're using the `listeners` config to enable SSL, you want to use `advertised.listeners` instead of `advertised.host.name`. Basically, the addition of different types of listeners required adding newer variants of the `advertised.*` options to allow specifying settings for the different listeners.

**Comment by kevinpauli** [comment]
@ewencp That was it! I had no idea such a property as advertised.listeners existed.  Thank you!!!
