### ISSUE TITLE
Need more clarity in documentation for upgrade/downgrade procedures and limitations across releases.

### ISSUE THREAD

**Issue by kaushiksrinivas** [confluentinc/kafka#937]
Hi Confluentic team,

Referring to the upgrade documentation from apache kafka's documentation page since we could not find a similar upgrade note from confluent documentations.
https://kafka.apache.org/34/documentation.html#upgrade_3_4_0

There is a confusion with respect to below statements from the above sectioned link of apache docs.

"If you are upgrading from a version prior to 2.1.x, please see the note below about the change to the schema used to store consumer offsets. Once you have changed the inter.broker.protocol.version to the latest version, it will not be possible to downgrade to a version prior to 2.1." (Capturing the statements as it is from the apache docs. Equivalent confluent kafka versions can be considered for the apache release versions)

The above statement mentions that the downgrade would not be possible to version prior to "2.1" in case of "upgrading the inter.broker.protocol.version to the latest version".

But, there is another statement made in the documentation in point 4 as below

"Restart the brokers one by one for the new protocol version to take effect. Once the brokers begin using the latest protocol version, it will no longer be possible to downgrade the cluster to an older version."

 These two statements are repeated across a lot of prior releases of kafka and is confusing.

Below are the questions:

Is downgrade not at all possible to "any" older version of kafka once the inter.broker.protocol.version is updated to latest version OR downgrades are not possible only to versions "<2.1" (appropriate confluent kafka versions)?
Suppose one takes an approach similar to upgrade even for the downgrade path. i.e. downgrade the inter.broker.protocol.version first to the previous version, next downgrade the software/code of kafka to previous release revision. Does downgrade work with this approach ?
Can these two questions be documented if the results are already known ?

Do we have a similar upgrade/downgrade documentation captured from confluent side ?

**Comment by mjsax** [comment]
Please reach out to the Kafka user mailing list about this: https://kafka.apache.org/contact
